version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_employee_test
    restart: always
    environment:
      POSTGRES_USER: juan_rojas
      POSTGRES_PASSWORD: juan_rojas_password
      POSTGRES_DB: db_employee
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: